### ISSUE TITLE
建议使用sqlhelper来处理SQL分页问题

### ISSUE THREAD

**Issue by fangjinuo** [noear/weed3#2]
刚刚查看了关于SQL分页相关的代码，每支持一个数据库，都会有相关打分页实现。

其实这个问题，sqlhelper已经帮你解决了，并且重分的利用了 ? 占位符。
你可以考虑一下

地址：[sqlhelper](https://github.com/fangjinuo/sqlhelper)

**Comment by noear** [comment]
好的，谢谢：）
可否为集成，提供一些帮助？

**Comment by fangjinuo** [comment]
[Github: SQLHelper integrate](https://fangjinuo.github.io/sqlhelper-pagination.html#pagination_how_to_integrate)
